void readInputFromFile();
void toAppLayer(char *inputString);
void mergeFrames(char *c);
void splitFrames(char *c);
void sendToPhysical(char synChar[], int n);
void convertCharToBinary(char *c, int n);
void toBinaryFirst();
void decimalToBinary(int n);
void toBinary(char *c);
void getFromPhysical(char fileFlag);
void addOddParityBits();
void storeDataInFile();
void storeDataInChckFile();
void sendDecodeToPhysical(char sNew[]);
void convertToString();
int myPower(int n, int m);
void removeOddParityBits(char *c);
void sendToDataLink(char myString[], int val);
void readBinaryDataFromFile();
void readDataReceivedFromClient();
void CRC();